// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package evs

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use this data source to query the detailed information list of the EVS disks within HuaweiCloud.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/huaweicloud/pulumi-huaweicloud/sdk/go/huaweicloud/Evs"
//	"github.com/pulumi/pulumi-huaweicloud/sdk/go/huaweicloud/Evs"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			cfg := config.New(ctx, "")
//			targetServer := cfg.RequireObject("targetServer")
//			_, err := Evs.GetVolumes(ctx, &evs.GetVolumesArgs{
//				ServerId: pulumi.StringRef(targetServer),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetVolumes(ctx *pulumi.Context, args *GetVolumesArgs, opts ...pulumi.InvokeOption) (*GetVolumesResult, error) {
	var rv GetVolumesResult
	err := ctx.Invoke("huaweicloud:Evs/getVolumes:getVolumes", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getVolumes.
type GetVolumesArgs struct {
	// Specifies the availability zone for the disks.
	AvailabilityZone *string `pulumi:"availabilityZone"`
	// Specifies the enterprise project ID for filtering.
	EnterpriseProjectId *string `pulumi:"enterpriseProjectId"`
	// Specifies the region in which to query the disk list.
	// If omitted, the provider-level region will be used.
	Region *string `pulumi:"region"`
	// Specifies the server ID to which the disks are attached.
	ServerId *string `pulumi:"serverId"`
	// Specifies whether the disk is shareable.
	Shareable *bool `pulumi:"shareable"`
	// Specifies the disk status. The valid values are as following:
	// + **FREEZED**
	// + **BIND_ERROR**
	// + **BINDING**
	// + **PENDING_DELETE**
	// + **PENDING_CREATE**
	// + **NOTIFYING**
	// + **NOTIFY_DELETE**
	// + **PENDING_UPDATE**
	// + **DOWN**
	// + **ACTIVE**
	// + **ELB**
	// + **ERROR**
	// + **VPN**
	Status *string `pulumi:"status"`
	// Specifies the included key/value pairs which associated with the desired disk.
	Tags map[string]string `pulumi:"tags"`
}

// A collection of values returned by getVolumes.
type GetVolumesResult struct {
	// The availability zone of the disk.
	AvailabilityZone *string `pulumi:"availabilityZone"`
	// The ID of the enterprise project associated with the disk.
	EnterpriseProjectId *string `pulumi:"enterpriseProjectId"`
	// The provider-assigned unique ID for this managed resource.
	Id     string  `pulumi:"id"`
	Region *string `pulumi:"region"`
	// The ID of the server to which the disk is attached.
	ServerId *string `pulumi:"serverId"`
	// Whether the disk is shareable.
	Shareable *bool `pulumi:"shareable"`
	// The disk status.
	Status *string `pulumi:"status"`
	// The disk tags.
	Tags map[string]string `pulumi:"tags"`
	// The detailed information of the disks. Structure is documented below.
	Volumes []GetVolumesVolume `pulumi:"volumes"`
}

func GetVolumesOutput(ctx *pulumi.Context, args GetVolumesOutputArgs, opts ...pulumi.InvokeOption) GetVolumesResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetVolumesResult, error) {
			args := v.(GetVolumesArgs)
			r, err := GetVolumes(ctx, &args, opts...)
			var s GetVolumesResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetVolumesResultOutput)
}

// A collection of arguments for invoking getVolumes.
type GetVolumesOutputArgs struct {
	// Specifies the availability zone for the disks.
	AvailabilityZone pulumi.StringPtrInput `pulumi:"availabilityZone"`
	// Specifies the enterprise project ID for filtering.
	EnterpriseProjectId pulumi.StringPtrInput `pulumi:"enterpriseProjectId"`
	// Specifies the region in which to query the disk list.
	// If omitted, the provider-level region will be used.
	Region pulumi.StringPtrInput `pulumi:"region"`
	// Specifies the server ID to which the disks are attached.
	ServerId pulumi.StringPtrInput `pulumi:"serverId"`
	// Specifies whether the disk is shareable.
	Shareable pulumi.BoolPtrInput `pulumi:"shareable"`
	// Specifies the disk status. The valid values are as following:
	// + **FREEZED**
	// + **BIND_ERROR**
	// + **BINDING**
	// + **PENDING_DELETE**
	// + **PENDING_CREATE**
	// + **NOTIFYING**
	// + **NOTIFY_DELETE**
	// + **PENDING_UPDATE**
	// + **DOWN**
	// + **ACTIVE**
	// + **ELB**
	// + **ERROR**
	// + **VPN**
	Status pulumi.StringPtrInput `pulumi:"status"`
	// Specifies the included key/value pairs which associated with the desired disk.
	Tags pulumi.StringMapInput `pulumi:"tags"`
}

func (GetVolumesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVolumesArgs)(nil)).Elem()
}

// A collection of values returned by getVolumes.
type GetVolumesResultOutput struct{ *pulumi.OutputState }

func (GetVolumesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVolumesResult)(nil)).Elem()
}

func (o GetVolumesResultOutput) ToGetVolumesResultOutput() GetVolumesResultOutput {
	return o
}

func (o GetVolumesResultOutput) ToGetVolumesResultOutputWithContext(ctx context.Context) GetVolumesResultOutput {
	return o
}

// The availability zone of the disk.
func (o GetVolumesResultOutput) AvailabilityZone() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetVolumesResult) *string { return v.AvailabilityZone }).(pulumi.StringPtrOutput)
}

// The ID of the enterprise project associated with the disk.
func (o GetVolumesResultOutput) EnterpriseProjectId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetVolumesResult) *string { return v.EnterpriseProjectId }).(pulumi.StringPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetVolumesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetVolumesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetVolumesResultOutput) Region() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetVolumesResult) *string { return v.Region }).(pulumi.StringPtrOutput)
}

// The ID of the server to which the disk is attached.
func (o GetVolumesResultOutput) ServerId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetVolumesResult) *string { return v.ServerId }).(pulumi.StringPtrOutput)
}

// Whether the disk is shareable.
func (o GetVolumesResultOutput) Shareable() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v GetVolumesResult) *bool { return v.Shareable }).(pulumi.BoolPtrOutput)
}

// The disk status.
func (o GetVolumesResultOutput) Status() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetVolumesResult) *string { return v.Status }).(pulumi.StringPtrOutput)
}

// The disk tags.
func (o GetVolumesResultOutput) Tags() pulumi.StringMapOutput {
	return o.ApplyT(func(v GetVolumesResult) map[string]string { return v.Tags }).(pulumi.StringMapOutput)
}

// The detailed information of the disks. Structure is documented below.
func (o GetVolumesResultOutput) Volumes() GetVolumesVolumeArrayOutput {
	return o.ApplyT(func(v GetVolumesResult) []GetVolumesVolume { return v.Volumes }).(GetVolumesVolumeArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetVolumesResultOutput{})
}
